
ifneq (true,$(RULES))

GCC_RISCV64_ELF_PKGNAME := gcc-riscv64-elf
GCC_RISCV64_ELF_PKG := $(PKG_RESULT_DIR)/$(GCC_RISCV64_ELF_PKGNAME).tar.bz2
GCC_PACKAGE_RESULTS += $(GCC_RISCV64_ELF_PKG)
GCC_PACKAGE_NAMES += $(GCC_RISCV64_PKGNAME)

else

gcc-riscv64-elf : $(GCC_RISCV64_ELF_PKG)

endif
