
ifneq (true,$(RULES))

GCC_RISCV32_ELF_PKGNAME := gcc-riscv32-elf
GCC_RISCV32_ELF_PKG := $(PKG_RESULT_DIR)/$(GCC_RISCV32_ELF_PKGNAME).tar.bz2
GCC_PACKAGE_RESULTS += $(GCC_RISCV32_ELF_PKG)
GCC_PACKAGE_NAMES += $(GCC_RISCV32_PKGNAME)

else

gcc-riscv32-elf : $(GCC_RISCV32_ELF_PKG)

endif
